
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: wsmi1289
  password: <%= ENV['TBF_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: willsmith


test:
  <<: *default
  database: tbf_test
  password: <%= ENV['APPNAME_DATABASE_PASSWORD_TEST'] %>

production:
  <<: *default
  database: tbf